/**
 * LANE-8: render projection seam unit tests.
 *
 * - classifyRenderViewer fails closed: owner needs a verified identity,
 *   engineer needs the explicit server grant, everything else is visitor.
 * - projectForViewer: the visitor projection excludes forbidden concepts
 *   even when fed full debug state; the engineer projection retains the
 *   debug information. Owner gets the single entry point, no raw findings.
 * - Label helpers: customer language, no em dashes, deterministic dates.
 */

import {
  classifyRenderViewer,
  observedMonthYear,
  projectForViewer,
  sourceLabelFor,
  supportLineFor,
} from "../render-projection";
import type {
  ProjectForViewerInput,
  RenderViewerClaim,
} from "../render-projection";
import type { PingObject } from "@/lib/ping/types";
import type {
  FYDFinding,
  FYDSiteSpec,
  ObjectGraph,
} from "../types";

/** Verbatim removal list (user-visible concepts the visitor must not see). */
const FORBIDDEN = [
  "Generated site demo",
  "Procedural clone proof",
  "Site record",
  "Why this?",
  "acceptance sequences",
  "proposalDigest",
  "baseStateDigest",
  "capability evaluation",
  "seeded",
  "unverified actor",
  "Demo addition",
  "Website statement",
  "Generated by FYD Social",
];

function pingObject(partial: Partial<PingObject> & { id: string }): PingObject {
  return {
    schema: "business",
    controllerId: "web:example",
    visibility: "public",
    title: "Test Business",
    description: "",
    fields: {},
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    provenance: {
      kind: "website-derived",
      ref: "https://example.com",
      derivedAt: "2026-09-15T00:00:00.000Z",
    },
    ...partial,
  };
}

/** A full debug state: validator findings with raw paths and debug copy. */
function debugInput(): ProjectForViewerInput {
  const objects = [
    pingObject({ id: "biz-1" }),
    pingObject({
      id: "svc-1",
      schema: "service",
      title: "Test Service",
      fields: { claimKind: "website_statement" },
    }),
    pingObject({
      id: "ovl-1",
      schema: "note",
      title: "Demo note",
      provenance: {
        kind: "overlay-authored",
        ref: "ping-event:fyd-seed-ovl-001",
        derivedAt: "2026-09-20T00:00:00.000Z",
      },
    }),
  ];
  const graph: ObjectGraph = { objects, relationships: [] };
  const findings: FYDFinding[] = [
    {
      severity: "error",
      authority: "fyd.sitespec.validator",
      resourceId: "spec",
      path: "pages[0].sections[3]",
      message: "unresolved directive debugging: section query matched nothing",
    },
    {
      severity: "warning",
      authority: "fyd.sitespec.validator",
      resourceId: "spec",
      path: "provenance.eventSequences",
      message: "acceptance sequences 65-83 from raw object IDs",
    },
    {
      severity: "info",
      authority: "fyd.sitespec.validator",
      resourceId: "spec",
      path: "capabilities",
      message: "capability evaluation with baseStateDigest abc123 and seeded actor",
    },
  ];
  const spec = {
    kind: "fyd.sitespec@1",
    ownerObjectId: "biz-1",
    version: 1,
    generator: {
      name: "fyd-site-generator",
      version: "test",
      generatedAt: "2026-09-26T10:00:00.000Z",
    },
  } as FYDSiteSpec;
  return { spec, graph, findings, renderable: true, siteId: "test-site" };
}

describe("classifyRenderViewer", () => {
  test("null, undefined, and empty claims are visitor", () => {
    expect(classifyRenderViewer(null)).toBe("visitor");
    expect(classifyRenderViewer(undefined)).toBe("visitor");
    expect(classifyRenderViewer({})).toBe("visitor");
  });

  test("unverified and id-less identities are visitor", () => {
    expect(classifyRenderViewer({ verified: false })).toBe("visitor");
    expect(
      classifyRenderViewer({ verified: false, identityId: "demo-owner" }),
    ).toBe("visitor");
    expect(classifyRenderViewer({ verified: true })).toBe("visitor");
    expect(
      classifyRenderViewer({ verified: true, identityId: "" }),
    ).toBe("visitor");
    expect(
      classifyRenderViewer({ verified: true, identityId: null }),
    ).toBe("visitor");
  });

  test("mode strings, roles, and demo shapes never elevate", () => {
    const sneaky = {
      mode: "owner",
      role: "admin",
      demo: true,
      practice: true,
      ownerMode: true,
    } as unknown as RenderViewerClaim;
    expect(classifyRenderViewer(sneaky)).toBe("visitor");
  });

  test("a verified identity with an id is owner", () => {
    expect(
      classifyRenderViewer({ verified: true, identityId: "owner-123" }),
    ).toBe("owner");
  });

  test("engineer requires the explicit grant, and wins over owner", () => {
    expect(classifyRenderViewer({ engineerGrant: true })).toBe("engineer");
    expect(
      classifyRenderViewer({
        verified: true,
        identityId: "owner-123",
        engineerGrant: true,
      }),
    ).toBe("engineer");
    expect(
      classifyRenderViewer({
        verified: true,
        identityId: "owner-123",
        engineerGrant: false,
      }),
    ).toBe("owner");
  });
});

describe("projectForViewer", () => {
  test("visitor: no findings, no owner entry, quiet source line", () => {
    const view = projectForViewer(debugInput(), "visitor");
    expect(view.viewerKind).toBe("visitor");
    expect(view.findings).toEqual([]);
    expect(view.showOwnerEntry).toBe(false);
    expect(view.ownerConsole).toBeNull();
    expect(view.source.sourceLabel).toBe("The business website");
    expect(view.source.observedLabel).toBe("September 2026");
    expect(view.source.honestyNote).toContain("not independently verified");
  });

  test("visitor view carries none of the forbidden concepts", () => {
    const view = projectForViewer(debugInput(), "visitor");
    // The findings (raw paths, acceptance sequences, digests) never reach
    // the visitor projection; the quiet source line is customer language.
    const chrome = JSON.stringify({
      findings: view.findings,
      source: view.source,
      showOwnerEntry: view.showOwnerEntry,
    });
    for (const term of FORBIDDEN) {
      expect(chrome).not.toContain(term);
    }
    expect(chrome).not.toContain("—");
  });

  test("owner: the single entry point, still no raw findings", () => {
    const view = projectForViewer(debugInput(), "owner");
    expect(view.viewerKind).toBe("owner");
    expect(view.showOwnerEntry).toBe(true);
    expect(view.ownerConsole).toEqual({ entryLabel: "Customize with FYD" });
    expect(view.findings).toEqual([]);
  });

  test("engineer: the full debug state is retained", () => {
    const input = debugInput();
    const view = projectForViewer(input, "engineer");
    expect(view.viewerKind).toBe("engineer");
    expect(view.showOwnerEntry).toBe(true);
    expect(view.findings).toEqual(input.findings);
    expect(view.findings.length).toBe(3);
    const chrome = JSON.stringify(view.findings);
    expect(chrome).toContain("acceptance sequences");
    expect(chrome).toContain("baseStateDigest");
  });

  test("same state, different projections: deterministic", () => {
    const a = JSON.stringify(projectForViewer(debugInput(), "visitor"));
    const b = JSON.stringify(projectForViewer(debugInput(), "visitor"));
    expect(a).toBe(b);
  });

  test("the projection does not widen the graph for the owner class", () => {
    const input = debugInput();
    const visitor = projectForViewer(input, "visitor");
    const owner = projectForViewer(input, "owner");
    expect(owner.graph).toBe(input.graph);
    expect(visitor.graph).toBe(input.graph);
  });
});

describe("label helpers", () => {
  test("observedMonthYear formats deterministically and fails closed", () => {
    expect(observedMonthYear("2026-09-15T00:00:00.000Z")).toBe(
      "September 2026",
    );
    expect(observedMonthYear("2026-01-02")).toBe("January 2026");
    expect(observedMonthYear(undefined)).toBe("date unknown");
    expect(observedMonthYear("not-a-date")).toBe("date unknown");
    expect(observedMonthYear("2026-13-01")).toBe("date unknown");
  });

  test("sourceLabelFor uses the fixed customer-language mapping", () => {
    expect(sourceLabelFor(pingObject({ id: "a" }))).toBe(
      "The business website",
    );
    expect(
      sourceLabelFor(
        pingObject({
          id: "b",
          fields: { claimKind: "feed_item" },
        }),
      ),
    ).toBe("The business's feed");
    expect(
      sourceLabelFor(
        pingObject({
          id: "c",
          provenance: {
            kind: "canonical-journal",
            ref: "ping-event:x",
            derivedAt: "2026-09-01T00:00:00.000Z",
          },
        }),
      ),
    ).toBe("Business information on file");
    expect(
      sourceLabelFor(
        pingObject({
          id: "d",
          provenance: {
            kind: "overlay-authored",
            ref: "ping-event:fyd-seed-ovl-001",
            derivedAt: "2026-09-01T00:00:00.000Z",
          },
        }),
      ),
    ).toBe("This demonstration");
  });

  test("supportLineFor renders direct/derived status without debug vocabulary", () => {
    const direct = supportLineFor(
      pingObject({ id: "a", fields: { claimKind: "website_statement" } }),
    );
    expect(direct).toBe("The business's own words. Not independently verified.");
    const demo = supportLineFor(
      pingObject({
        id: "d",
        provenance: {
          kind: "overlay-authored",
          ref: "ping-event:fyd-seed-ovl-001",
          derivedAt: "2026-09-01T00:00:00.000Z",
        },
      }),
    );
    expect(demo).toContain("demonstration");
    for (const term of FORBIDDEN) {
      expect(direct).not.toContain(term);
      expect(demo).not.toContain(term);
    }
    expect(direct).not.toContain("—");
    expect(demo).not.toContain("—");
  });
});
