/** Public education based on the published architecture. Maturity is documented scope, not a deployment probe. */
export const REPOSITORY_URL="https://github.com/ngesk2/crx-runtime";
export const SOURCE_ORIGIN="http://100.79.154.43:3100";
export const primitives=[
{id:"events",label:"Events",summary:"A durable record of something that happened.",why:"A decision needs a history that can be found again.",consumes:"An observation with identity, time, and source.",produces:"A validated event that later work can reference.",authority:"The event authority owns the canonical record.",verify:"Inspect the event identity, source, version, and causal references.",maturity:"In development",source:"/technology/events"},
{id:"evidence",label:"Evidence",summary:"The support behind a claim.",why:"A convincing answer and a supported answer are different things.",consumes:"A source, an observation, or the result of work.",produces:"An attributable basis for a claim, including its limits.",authority:"Evidence authority; presentation cannot promote a claim into fact.",verify:"Follow the source and inspect what it actually supports.",maturity:"Documented",source:"/technology/evidence"},
{id:"identity",label:"Identity",summary:"Who or what is involved, within which business.",why:"Context and permission must not drift between tenants.",consumes:"A resolved actor and tenant context.",produces:"An identity that records and permissions can refer to.",authority:"Identity and tenant authorities.",verify:"Check which tenant and actor a record belongs to.",maturity:"Direction",source:"/technology/tenantos"},
{id:"missions",label:"Missions",summary:"An explicit objective for a piece of work.",why:"Useful work needs a purpose and a way to judge its outcome.",consumes:"An objective, context, and a permitted scope.",produces:"Related work and a recorded outcome.",authority:"Mission authority; an interface displays its records.",verify:"Trace the objective to the work and its evidence.",maturity:"Documented",source:"/technology/agents"},
{id:"workers",label:"Workers",summary:"Executors of bounded work.",why:"A model’s proposal needs a separate execution boundary.",consumes:"A work request and the capabilities granted to it.",produces:"A result or an explicit failure, with evidence.",authority:"The worker executes inside existing capability boundaries.",verify:"Inspect the request, executor, permitted action, and result.",maturity:"Documented",source:"/technology/agents"},
{id:"capabilities",label:"Capabilities",summary:"Specific permission to perform a specific action.",why:"Knowing what to do does not grant the right to do it.",consumes:"Identity, scope, and an authority decision.",produces:"A bounded grant, or a denial.",authority:"Capability authority; default deny is the documented posture.",verify:"Check what was granted and whether the action stayed in scope.",maturity:"Documented",source:"/technology/agents"},
{id:"authority",label:"Authority",summary:"The owner of a particular decision.",why:"Competing sources of truth make a system impossible to reason about.",consumes:"A proposed change and the rules for that concern.",produces:"An authoritative decision that other parts can reference.",authority:"One authority per concern, with human decision boundaries.",verify:"Ask which authority decided and which evidence it used.",maturity:"Design principle",source:"/about"},
{id:"replay",label:"Replay",summary:"Reconstruct a result from recorded history.",why:"The reasoning behind an outcome should be inspectable later.",consumes:"Causal history, relevant inputs, and versions.",produces:"A reconstruction that can be compared with the original.",authority:"Replay machinery preserves the original authority boundaries.",verify:"Compare ordering and canonical results; account for external inputs.",maturity:"Experimental",source:"/technology/replay"},
{id:"witness",label:"Witness",summary:"A checkable attestation about an execution.",why:"A result needs an attributable record of how it came about.",consumes:"An execution and its canonical result.",produces:"An attestation connecting the actor, authority, and result.",authority:"Witness machinery; a witness does not grant permission.",verify:"Check what the attestation covers and what remains outside it.",maturity:"Experimental",source:"/technology/replay"},
{id:"lineage",label:"Lineage",summary:"The connections from cause to consequence.",why:"A final answer alone cannot explain why it exists.",consumes:"References between observations, events, work, and results.",produces:"A path back through the decisions and sources.",authority:"The authorities that own the linked records.",verify:"Follow each link; a missing link remains a gap.",maturity:"Documented",source:"/technology/evidence"},
{id:"knowledge",label:"Knowledge",summary:"Understanding with sources and relationships.",why:"What a business learns should remain useful to the next person.",consumes:"Recorded activity and attributable evidence.",produces:"Claims and relationships that can be inspected and revised.",authority:"Knowledge authorities; the website projects published records.",verify:"Inspect provenance and contradictions, not just the latest wording.",maturity:"In development",source:"/technology/continuity"},
{id:"human-boundaries",label:"Human decisions",summary:"Judgment remains with the people responsible.",why:"Automation should not silently expand its own authority.",consumes:"A proposal, its evidence, and the required decision scope.",produces:"An explicit decision, or a hold while a decision is missing.",authority:"The authorized human for the relevant decision.",verify:"Check the decision’s scope; a proposal is not an approval.",maturity:"Design principle",source:"/technology/agents"},
{id:"persistence",label:"Persistence",summary:"Records that outlast a process or conversation.",why:"Restarting software should not erase the reason for prior work.",consumes:"Accepted records and their causal references.",produces:"History available to later reads and reconstruction.",authority:"The store behind the relevant record authority.",verify:"Check the storage and restart guarantees for that particular path.",maturity:"In development",source:"/technology/events"},
{id:"external-execution",label:"External execution",summary:"Work across a machine or service boundary.",why:"Outside systems can fail or return an uncertain result.",consumes:"A scoped request and explicit execution inputs.",produces:"A result, evidence, or a clearly identified failure.",authority:"Existing identity, capability, and execution authorities.",verify:"Check the actual effect before repeating an uncertain action.",maturity:"Experimental",source:"/technology/agents"}
];
export const principles=[
{title:"Knowledge should compound.",summary:"Keep what the work teaches you.",detail:"Preserve the source and the history so the next person can build on what is already known. A new answer should not erase the evidence behind an earlier one.",source:"/technology/continuity"},
{title:"Prove it.",summary:"A claim should have somewhere to point.",detail:"Evidence connects an answer to its source. Uncertainty and missing information stay visible, so people can decide what deserves their confidence.",source:"/about"},
{title:"Humans stay in control.",summary:"Permission is a decision.",detail:"An agent may propose. A worker may execute within a grant. The people responsible retain the decisions that require their judgment.",source:"/about"}
];
export const flowItems=[
{label:"Observe",example:"“The kitchen tap is leaking again. Can you take a look?”",title:"Start with what happened.",detail:"A customer inquiry, a team note, a form, or an API can provide the input. Capture the source before interpreting it.",tag:"Input",glyph:"↘"},
{label:"Remember",example:"Keep the request with its source and date. A follow-up can refer back to this exact inquiry.",title:"Give it a durable record.",detail:"Events retain identity, source, and causal history. The next conversation can start with something more useful than a blank page.",tag:"Events",glyph:"≡"},
{label:"Connect",example:"Link the request to the published repair service. A previous visit stays unknown until a record supports it.",title:"Keep the relationships.",detail:"A record becomes useful in context: the business it belongs to, the work it concerns, and the evidence behind it. Business graph expansion remains a direction.",tag:"Knowledge",glyph:"⌘"},
{label:"Act",example:"Prepare a reply within the permitted scope. Booking a visit still needs the right authorization.",title:"Work inside a boundary.",detail:"Missions express objectives. Workers carry out bounded work. Capability grants determine what is permitted; a proposal alone grants nothing.",tag:"Authority",glyph:"↗"},
{label:"Prove",example:"Record what was sent and what remains unanswered. An uncertain delivery stays unresolved until checked.",title:"Bring the evidence back.",detail:"Results should connect to their causes and sources. Replay and witness mechanisms are being developed to make that history checkable.",tag:"Evidence",glyph:"◎"}
];
