/**
 * FYD Social generated-site demo: Coppersmith Plumbing & HVAC.
 *
 * Second procedural-clone proof (grill plan item 2): the page below is
 * compiled from REAL fetched bytes of https://www.coppersmithplumbing.com/
 * (observed 2026-09-21T12:01:10.844Z) through the real pipeline stages, then
 * generateSiteSpec, then rendered from the declarative spec. The graph
 * fixture is machine-generated by /tmp/second-site-run/run.ts, never
 * hand-written. No hand-layout for this company exists anywhere in the
 * pipeline.
 *
 * The spec is validated before render. An invalid spec never renders.
 */

import { SiteClient } from "../happy-place/site-client";
import { COPPERSMITH_GRAPH } from "@/fyd/proceduralize/__fixtures__/coppersmith-graph";
import { generateSiteSpec } from "@/fyd/proceduralize/generator";
import { isRenderable, validateSiteSpec } from "@/fyd/sitespec/validator";

export const metadata = {
  title: "Coppersmith Plumbing & HVAC | FYD Social Generated Site",
  description:
    "A procedurally generated site for Coppersmith Plumbing & HVAC, compiled by FYD Social from real website-ingestion bytes.",
};

export default function CoppersmithDemoPage() {
  const spec = generateSiteSpec(COPPERSMITH_GRAPH, {
    generatedAt: "2026-09-21T12:01:10.844Z",
  });
  const knownSchemas = new Set(COPPERSMITH_GRAPH.objects.map((o) => o.schema));
  const findings = validateSiteSpec(spec, knownSchemas);
  const renderable = isRenderable(findings);

  return (
    <main className="min-h-screen bg-background">
      <SiteClient
        spec={spec}
        graph={COPPERSMITH_GRAPH}
        findings={findings}
        renderable={renderable}
      />
    </main>
  );
}
