/**
 * LANE-8: client shell for the FYD Social generated-site demo pages.
 *
 * The shell consumes ONLY the ProjectedSiteView: the page server component
 * resolves the viewer class and projects the compiled artifacts through
 * projectForViewer, and this shell renders the projection. It never sees
 * raw state, validator findings (unless engineer), or demo-owner
 * constructs.
 *
 * Visitor: business content only, plus the quiet Source footer. No demo
 * framing, no validator/provenance debug, no structured editor.
 * Owner: the visitor page plus the single "Customize with FYD" entry point
 * (OwnerPanel; lane 9 builds the conversational UX behind it).
 * Engineer: the current debug material (structured editor, validator
 * notes, provenance sentence) behind the deliberate ?fyd_advanced=1 +
 * server-grant surface.
 */

"use client";

import { useEffect, useMemo, useState } from "react";
import { SitePageView, resolveQuery } from "@/fyd/components/renderer";
import { getComponentDef } from "@/fyd/components/registry";
import { applySitePatch, proposeSitePatch, type SiteIntent, type SitePatchBody } from "@/fyd/proceduralize/patch";
import type {
  FYDSiteSpec,
  FYDThemeTokens,
  ObjectGraph,
  ViewerContext,
} from "@/fyd/sitespec/types";
import { FydMotionFallback } from "@/fyd/components/fyd-motion-fallback";
import { ObjectOverlay } from "@/fyd/components/object-overlay";
import { edgeClientScript } from "@/fyd/edge/client";
import { MarginObjectLayer } from "@/fyd/ui/object-layer/MarginObjectLayer";
import { selectMarginObjects } from "@/fyd/ui/object-layer/margin-select";
import { OwnerEntryPoint, OwnerPanel } from "../../build/[siteId]/owner-panel";
import type { ProjectedSiteView } from "@/fyd/sitespec/render-projection";

declare global {
  interface Window {
    /** Published by the edge client script: opens the edge object sheet. */
    __fydEdgeOpen?: (objectId: string, trigger: unknown) => void;
  }
}

const VIEWER: ViewerContext = { viewerId: null, displayName: null };

/**
 * Provenance footer sentence, rendered from spec.provenance (QA-TRUTH F-001).
 * The acceptance-sequence parenthetical appears only when the spec carries
 * an eventSequences pair; it is never hardcoded. Fail closed on display:
 * absent provenance data omits the parenthetical rather than printing a
 * placeholder or a wrong number. ENGINEER ONLY: never on the visitor page.
 */
function provenanceSentence(spec: FYDSiteSpec): string {
  const provenance = spec.provenance;
  const seq = provenance?.eventSequences;
  const seqText =
    Array.isArray(seq) && seq.length === 2
      ? ` (acceptance sequences ${seq[0]}-${seq[1]})`
      : "";
  const source = provenance?.source ?? "website-ingestion";
  return (
    `Generated by FYD Social from a ${source} object graph${seqText}. ` +
    "All claims on this page are website statements, never verified fact."
  );
}

export function SiteClient({ view }: { view: ProjectedSiteView }) {
  const {
    spec: initialSpec,
    graph,
    findings,
    renderable,
    siteId,
    heroMedia,
    galleryMedia,
    viewerKind,
  } = view;
  const [spec, setSpec] = useState(initialSpec);
  const [activeSlug, setActiveSlug] = useState(
    initialSpec.navigation[0]?.pageSlug ?? "home",
  );
  const [proposal, setProposal] = useState<SitePatchBody | null>(null);
  const [patchError, setPatchError] = useState<string | null>(null);
  const [overlayObjectId, setOverlayObjectId] = useState<string | null>(null);

  const isEngineer = viewerKind === "engineer";

  const ctx = useMemo(
    () => ({
      spec,
      graph,
      viewer: VIEWER,
      siteId,
      heroMedia,
      galleryMedia,
      objectMedia: view.objectMedia,
      viewerKind,
    }),
    [spec, graph, siteId, heroMedia, galleryMedia, viewerKind, view.objectMedia],
  );
  const page = spec.pages.find((p) => p.slug === activeSlug) ?? spec.pages[0];
  // MARGIN-1 (Nolan 2026-09-25): the page-level edge/margin object layer.
  // graph -> eligibility -> contextual selection -> projection ->
  // MarginObjectLayer -> browser. Deterministic eligibility first;
  // the layer is the production feed (no debug flag in this path).
  const marginObjects = useMemo(
    () =>
      page
        ? selectMarginObjects({
            graph,
            page,
            ownerId: spec.ownerObjectId,
            siteId: siteId ?? "",
          })
        : [],
    [graph, page, spec.ownerObjectId, siteId],
  );
  // Object doorway: intercept taps/clicks on /o/ links. EDGE-1 routes them
  // into the edge object sheet (the functional doorway into the authorized
  // graph). The legacy ObjectOverlay remains only as a fallback when the
  // edge script failed to load. Close returns to exact scroll position
  // (handled by the sheet / ObjectOverlay).
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const link = target.closest('a[href^="/o/"]') as HTMLAnchorElement | null;
      if (!link) return;
      // Let modifier clicks (new tab), #ask links, and explicit
      // full-navigation links (data-fyd-open-full) pass through.
      if (e.metaKey || e.ctrlKey || e.shiftKey) return;
      if (link.hasAttribute("data-fyd-open-full")) return;
      const href = link.getAttribute("href") || "";
      if (href.includes("#ask")) return;
      const match = href.match(/^\/o\/([^#?]+)/);
      if (!match) return;
      const objectId = decodeURIComponent(match[1]);
      // Verify the object exists in the public graph.
      const obj = graph.objects.find((o) => o.id === objectId);
      if (!obj) return;
      e.preventDefault();
      const edgeOpen = window.__fydEdgeOpen;
      if (typeof edgeOpen === "function") {
        edgeOpen(objectId, link);
      } else {
        setOverlayObjectId(objectId);
      }
    };
    document.addEventListener("click", handler);
    return () => document.removeEventListener("click", handler);
  }, [graph]);

  const runIntent = (intent: SiteIntent) => {
    setPatchError(null);
    const result = proposeSitePatch(spec, intent);
    if (!result.ok || !result.proposal) {
      setPatchError(result.error ?? "Invalid intent.");
      setProposal(null);
      return;
    }
    setProposal(result.proposal);
  };

  const approveProposal = () => {
    if (!proposal) return;
    setSpec(applySitePatch(spec, proposal));
    setProposal(null);
  };

  return (
    <div>
      <FydMotionFallback />
      {/* EDGE-1: tap-to-expand edge-object client. The script publishes
          window.__fydEdgeOpen, which the /o/ interceptor above routes
          doorway taps into. */}
      {siteId ? (
        <script dangerouslySetInnerHTML={{ __html: edgeClientScript(siteId) }} />
      ) : null}
      {/* MARGIN-1: page-level margin object layer (very-right overlay on
          mobile). Mounted always; no debug flag in the production path. */}
      {renderable ? <MarginObjectLayer objects={marginObjects} /> : null}
      {overlayObjectId && (() => {
        const obj = graph.objects.find((o) => o.id === overlayObjectId);
        if (!obj) return null;
        return (
          <ObjectOverlay
            object={obj}
            graph={graph}
            siteId={siteId ?? ""}
            onClose={() => setOverlayObjectId(null)}
            viewerKind={viewerKind}
          />
        );
      })()}
      {/* Site header. Product surface: the FYD Social kicker and the page
          tabs. No demo framing ("Generated site demo" / "Procedural clone
          proof" never render on any projection). The hero section owns the
          business h1. */}
      <header className="border-b border-border-soft bg-background">
        <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-3 px-4 py-4 sm:px-6">
          <p className="text-xs font-semibold uppercase tracking-widest text-accent">
            FYD Social
          </p>
        </div>
        <nav className="mx-auto flex max-w-5xl gap-1 overflow-x-auto px-4 pb-3 sm:px-6" aria-label="Generated pages">
          {spec.navigation.map((n) => (
            <button
              key={n.pageSlug}
              onClick={() => setActiveSlug(n.pageSlug)}
              className={
                "rounded px-4 py-2 text-sm font-medium " +
                (n.pageSlug === activeSlug
                  ? "bg-primary text-primary-foreground"
                  : "text-accent hover:bg-surface")
              }
            >
              {n.label}
            </button>
          ))}
        </nav>
      </header>

      {/* Validation status. An invalid spec never renders. Non-engineers
          see a generic message; only engineers see the raw findings. */}
      {!renderable ? (
        <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6">
          <h2 className="text-lg font-semibold">Site preview unavailable</h2>
          {isEngineer ? (
            <ul className="mt-3 list-disc pl-5 text-sm">
              {findings
                .filter((f) => f.severity === "error")
                .map((f, i) => (
                  <li key={i}>
                    {f.path}: {f.message}
                  </li>
                ))}
            </ul>
          ) : (
            <p className="mt-2 text-sm text-accent">
              This site preview is temporarily unavailable. Please check back
              later.
            </p>
          )}
        </div>
      ) : (
        page && <SitePageView key={page.slug + JSON.stringify(spec.themeTokens)} page={page} ctx={ctx} />
      )}

      {/* Source footer. Quiet progressive disclosure for every viewer
          class: source, observed date, direct/derived status. Debug
          provenance (ingestion vocabulary, acceptance sequences, validator
          notes) is engineer-only. */}
      <footer className="border-t border-border-soft bg-surface">
        <div className="mx-auto max-w-5xl px-4 py-6 text-sm text-accent sm:px-6">
          <details className="fyd-page-source">
            <summary className="cursor-pointer underline decoration-dotted underline-offset-2">
              Source
            </summary>
            <div className="mt-2 space-y-1">
              <p>Source: {view.source.sourceLabel}</p>
              <p>Observed: {view.source.observedLabel}</p>
              <p>{view.source.honestyNote}</p>
            </div>
          </details>
          {isEngineer && (
            <>
              <p className="mt-4">{provenanceSentence(spec)}</p>
              {findings.filter((f) => f.severity !== "error").length > 0 && (
                <details className="mt-2">
                  <summary className="cursor-pointer underline">
                    Validator notes ({findings.filter((f) => f.severity !== "error").length})
                  </summary>
                  <ul className="mt-2 list-disc pl-5">
                    {findings
                      .filter((f) => f.severity !== "error")
                      .map((f, i) => (
                        <li key={i}>
                          [{f.severity}] {f.path}: {f.message}
                        </li>
                      ))}
                  </ul>
                </details>
              )}
            </>
          )}
        </div>
      </footer>

      {/* LANE-8: the ONE owner affordance. The engineer gets the full
          conversational and digest machinery; the verified owner gets
          exactly one "Customize with FYD" entry point (lane 9 builds the
          conversational UX behind it). Visitors get neither. */}
      {view.showOwnerEntry && siteId ? (
        isEngineer ? (
          <OwnerPanel siteId={siteId} viewerKind={viewerKind} />
        ) : (
          <OwnerEntryPoint />
        )
      ) : null}

      {/* Structured editor. ENGINEER ONLY: the raw customization machinery
          is debug material, never on the visitor or owner page. */}
      {isEngineer && (
        <section className="border-t-4 border-primary bg-background">
          <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6">
            <h2 className="text-2xl font-semibold">Customize this site</h2>
            <p className="mt-2 max-w-2xl text-sm text-accent">
              Structured editing only: reorder sections, hide or show them, pick
              featured objects, propose copy edits, tune basic design tokens.
              Every change becomes a proposal with a digest. Copy and token edits
              stay drafts until the digest is approved.
            </p>
            {page && (
              <EditorPanel
                spec={spec}
                graph={graph}
                pageSlug={page.slug}
                onIntent={runIntent}
              />
            )}
            {patchError && (
              <p className="mt-4 rounded border border-red-300 bg-red-50 p-3 text-sm text-red-700">
                {patchError}
              </p>
            )}
            {proposal && (
              <div className="mt-4 rounded border border-border-soft bg-surface p-4">
                <h3 className="font-semibold">Proposed change</h3>
                <pre className="mt-2 overflow-x-auto rounded bg-primary p-3 text-xs text-primary-foreground">
                  {JSON.stringify(proposal, null, 2)}
                </pre>
                <p className="mt-2 text-xs text-accent">
                  Digest: <code className="break-all">{proposal.proposalDigest}</code>
                </p>
                <p className="mt-1 text-xs text-accent">
                  Draft only. Approving applies it to this demo preview.
                </p>
                <button
                  onClick={approveProposal}
                  className="mt-3 rounded bg-honey px-5 py-2 text-sm font-semibold text-honey-foreground"
                >
                  Approve and apply to preview
                </button>
              </div>
            )}
          </div>
        </section>
      )}
    </div>
  );
}

function EditorPanel({
  spec,
  graph,
  pageSlug,
  onIntent,
}: {
  spec: FYDSiteSpec;
  graph: ObjectGraph;
  pageSlug: string;
  onIntent: (intent: SiteIntent) => void;
}) {
  const page = spec.pages.find((p) => p.slug === pageSlug);
  const [copyDrafts, setCopyDrafts] = useState<Record<string, { heading: string; copy: string }>>({});
  const [tokenDrafts, setTokenDrafts] = useState<Partial<Record<keyof FYDThemeTokens, string>>>({});
  if (!page) return null;

  return (
    <div className="mt-6 flex flex-col gap-4">
      {page.sections.map((s, i) => {
        const def = getComponentDef(s.component);
        const objects = resolveQuery(s.query, graph, spec.ownerObjectId);
        const draft = copyDrafts[s.id] ?? { heading: s.presentation.heading ?? "", copy: s.presentation.copy ?? "" };
        return (
          <div key={s.id} className="rounded border border-border-soft bg-surface p-4">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div>
                <p className="font-semibold">
                  {def?.label ?? s.component}{" "}
                  <span className="text-xs font-normal text-accent">({s.id})</span>
                </p>
                <p className="text-xs text-accent">
                  {objects.length} object{objects.length === 1 ? "" : "s"} resolved
                  {s.presentation.hidden ? " - hidden" : ""}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button
                  className="rounded border border-border-soft px-3 py-1 text-xs"
                  disabled={i === 0}
                  onClick={() => onIntent({ kind: "reorder_section", pageSlug, sectionId: s.id, toIndex: i - 1 })}
                >
                  Up
                </button>
                <button
                  className="rounded border border-border-soft px-3 py-1 text-xs"
                  disabled={i === page.sections.length - 1}
                  onClick={() => onIntent({ kind: "reorder_section", pageSlug, sectionId: s.id, toIndex: i + 1 })}
                >
                  Down
                </button>
                <button
                  className="rounded border border-border-soft px-3 py-1 text-xs"
                  onClick={() => onIntent({ kind: "toggle_section", pageSlug, sectionId: s.id, hidden: !s.presentation.hidden })}
                >
                  {s.presentation.hidden ? "Show" : "Hide"}
                </button>
              </div>
            </div>

            {objects.length > 1 && (
              <div className="mt-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-accent">Featured</p>
                <div className="mt-1 flex flex-wrap gap-2">
                  {objects.map((o) => {
                    const active = s.presentation.featuredIds?.includes(o.id) ?? false;
                    return (
                      <button
                        key={o.id}
                        onClick={() => {
                          const current = new Set(s.presentation.featuredIds ?? objects.map((x) => x.id));
                          if (active) current.delete(o.id);
                          else current.add(o.id);
                          onIntent({ kind: "set_featured", pageSlug, sectionId: s.id, objectIds: [...current] });
                        }}
                        className={
                          "rounded-full border px-3 py-1 text-xs " +
                          (active ? "bg-primary text-primary-foreground" : "border-border-soft")
                        }
                      >
                        {o.title}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2">
              <input
                className="rounded border border-border-soft bg-background px-3 py-2 text-sm"
                placeholder="Proposed heading"
                value={draft.heading}
                onChange={(e) =>
                  setCopyDrafts({ ...copyDrafts, [s.id]: { ...draft, heading: e.target.value } })
                }
                aria-label={"Proposed heading for " + s.id}
              />
              <input
                className="rounded border border-border-soft bg-background px-3 py-2 text-sm"
                placeholder="Proposed copy"
                value={draft.copy}
                onChange={(e) =>
                  setCopyDrafts({ ...copyDrafts, [s.id]: { ...draft, copy: e.target.value } })
                }
                aria-label={"Proposed copy for " + s.id}
              />
            </div>
            <button
              className="mt-2 rounded border border-border-soft px-3 py-1 text-xs"
              onClick={() =>
                onIntent({
                  kind: "edit_copy",
                  pageSlug,
                  sectionId: s.id,
                  heading: draft.heading || undefined,
                  copy: draft.copy || undefined,
                })
              }
            >
              Propose copy edit
            </button>
          </div>
        );
      })}

      <div className="rounded border border-border-soft bg-surface p-4">
        <p className="font-semibold">Design tokens</p>
        <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2">
          {(["accent", "surface", "ink"] as (keyof FYDThemeTokens)[]).map((token) => (
            <label key={token} className="flex items-center gap-2 text-sm">
              <span className="w-20 capitalize text-accent">{token}</span>
              <input
                className="min-w-0 flex-1 rounded border border-border-soft bg-background px-3 py-2 text-sm"
                value={tokenDrafts[token] ?? String(spec.themeTokens[token])}
                onChange={(e) => setTokenDrafts({ ...tokenDrafts, [token]: e.target.value })}
              />
              <button
                className="rounded border border-border-soft px-3 py-1 text-xs"
                onClick={() => {
                  const value = (tokenDrafts[token] ?? String(spec.themeTokens[token])).trim();
                  onIntent({ kind: "set_theme_token", token, value });
                }}
              >
                Propose
              </button>
            </label>
          ))}
        </div>
      </div>
    </div>
  );
}
