import {chromium,firefox,webkit} from '/home/nolan/projects/fyd-editorial-template/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch();const rows=[];const faults=[];const url='http://127.0.0.1:3213/';
const widths=[320,360,375,390,414,540,768,820,1024,1280,1440,1920];
for(const width of widths)for(const height of [568,844])for(const motion of ['reduce','no-preference']){
 const page=await browser.newPage({viewport:{width,height},reducedMotion:motion});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
 await page.locator('#fyd').scrollIntoViewIfNeeded();await page.locator('.ed-service-list button').first().waitFor();
 await page.getByRole('button',{name:'Happy Place',exact:false}).click();await page.locator('.ed-service-list button').last().click();await page.locator('.ed-service-detail summary').click();
 const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].some(i=>!i.complete||i.naturalWidth===0),h1:document.querySelectorAll('h1').length,animations:document.getAnimations().filter(a=>a.playState==='running').length,smallTargets:[...document.querySelectorAll('button')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&(r.height<44||r.width<44)}).map(e=>e.textContent),outside:[...document.querySelectorAll('button,input,a')].filter(e=>{let r=e.getBoundingClientRect();return r.width>0&&(r.left<-.5||r.right>innerWidth+.5)&&!e.classList.contains('ed-skip')}).map(e=>e.textContent)}));
 rows.push({width,height,motion,...result,errors});if(result.overflow||result.broken||result.h1!==1||errors.length||result.smallTargets.length||result.outside.length||(motion==='reduce'&&result.animations))faults.push(rows.at(-1));await page.close();
}
const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await page.goto(url,{waitUntil:'networkidle'});
await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').innerText(),'Skip to content');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>location.hash),'#main');
await page.getByRole('button',{name:'Menu'}).click();assert.equal(await page.getByRole('button',{name:'Close',exact:false}).getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Menu'}).getAttribute('aria-expanded'),'false');assert.equal(await page.locator(':focus').innerText(),'Menu\n+');
await page.getByRole('button',{name:'continuity',exact:false}).click();assert((await page.locator('.ed-results').innerText()).includes('PING'));
await page.getByLabel('Find a product, capability, or article').fill('guaranteed price tomorrow');await page.getByRole('button',{name:'Search published knowledge'}).click();assert((await page.locator('.ed-results').innerText()).includes('No published record'));
await page.locator('#fyd').scrollIntoViewIfNeeded();await page.locator('.ed-service-list button').first().waitFor();await page.locator('.ed-service-list button').first().focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.ed-service-list button').first().getAttribute('aria-pressed'),'true');
const a11y=[];for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.addScriptTag({path:'/home/nolan/projects/ping/node_modules/axe-core/axe.min.js'});const result=await page.evaluate(async()=>await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));a11y.push({width,violations:result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});}
await fs.writeFile('evidence/validation.json',JSON.stringify({rows,faults,keyboard:true,unknownSearch:true,a11y},null,2));console.log({matrix:rows.length,faults,a11y,keyboard:true,unknownSearch:true});
for(const width of [320,375,390,768,1024,1280,1440,1920]){await page.setViewportSize({width,height:width<768?844:1050});await page.goto(url,{waitUntil:'networkidle'});await page.locator('#fyd').scrollIntoViewIfNeeded();await page.locator('.ed-service-list button').first().waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`evidence/final-${width}.png`,fullPage:true});if([390,1440].includes(width)){await page.screenshot({path:`evidence/final-${width}-first.png`});await page.locator('#fyd').screenshot({path:`evidence/final-${width}-proof.png`});}}
await browser.close();if(faults.length||a11y.some(x=>x.violations.length))process.exitCode=1;
