/**
 * GENERATED by scripts/fyd-contract-digests.mjs. Do not edit by hand.
 *
 * Semantic contract digests (Q-C-03). These pin the render contract:
 * - COMPONENT_CATALOG_DIGEST covers the section component registry
 *   (src/fyd/components/registry.ts); any catalog change rotates it.
 * - THEME_TOKENS_DIGEST covers FYDThemeTokens and its token interfaces
 *   (src/fyd/sitespec/types.ts); any token-shape change rotates it.
 *
 * render-model.ts derives RENDERER_VERSION and DESIGN_TOKEN_VERSION from
 * these digests, so a stale pin is a contract violation, not a silent
 * drift. Regenerate with: node scripts/fyd-contract-digests.mjs
 */
export const COMPONENT_CATALOG_DIGEST = "df967e6f3fd17d7a87fbe1cb5201712eec5614449f311c38b1c4d314d700cfbb";
export const THEME_TOKENS_DIGEST = "821c658c14dd3c2eea6ab4bc66f94269c16b2dd280f822ddbc0997cf4d6995cb";
export const CONTRACT_DIGEST_SOURCES = {
  registry: "src/fyd/components/registry.ts",
  types: "src/fyd/sitespec/types.ts",
} as const;
