/**
 * GENERATED by scripts/fyd-contract-digests.mjs. Do not edit by hand.
 *
 * Semantic contract digests (Q-C-03). These pin the render contract:
 * - COMPONENT_CATALOG_DIGEST covers the section component registry
 *   (src/fyd/components/registry.ts); any catalog change rotates it.
 * - THEME_TOKENS_DIGEST covers FYDThemeTokens and its token interfaces
 *   (src/fyd/sitespec/types.ts); any token-shape change rotates it.
 *
 * render-model.ts derives RENDERER_VERSION and DESIGN_TOKEN_VERSION from
 * these digests, so a stale pin is a contract violation, not a silent
 * drift. Regenerate with: node scripts/fyd-contract-digests.mjs
 */
export const COMPONENT_CATALOG_DIGEST = "a0a5c0f4b1e90df17d4d001d54660623f4620adea5024533c6afe26683854584";
export const THEME_TOKENS_DIGEST = "fd23fe0cbc1736ebaf34e9a070ca8f053a721d276a66e2eb96cb0cf72e5366f5";
export const CONTRACT_DIGEST_SOURCES = {
  registry: "src/fyd/components/registry.ts",
  types: "src/fyd/sitespec/types.ts",
} as const;
