const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('\\\\wsl.localhost\\Ubuntu\\home\\nolan\\projects\\fyd-editorial-template\\node_modules\\playwright');
const base='http://127.0.0.1:3214';
(async()=>{
const browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true});
const matrix=[],a11y=[],failures=[],interactions={};
const errors=[];
for(const width of [320,360,375,390,414,540,768,820,1024,1280,1440,1920])for(const height of [568,844])for(const reducedMotion of ['reduce','no-preference']){
const page=await browser.newPage({viewport:{width,height},reducedMotion});page.on('pageerror',e=>errors.push({width,error:e.message}));
await page.goto(base,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
await page.locator('#fyd').scrollIntoViewIfNeeded();await page.locator('.ed-service-list button').first().waitFor();
const row=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,h1:document.querySelectorAll('h1').length,broken:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src),smallButtons:[...document.querySelectorAll('button')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&(r.width<43.5||r.height<43.5)}).map(e=>e.getAttribute('aria-label')||e.innerText),outside:[...document.querySelectorAll('button,input,a')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left<-.5||r.right>innerWidth+.5)&&!e.classList.contains('ed-skip')}).map(e=>({text:e.innerText,label:e.getAttribute('aria-label')})),runningAnimations:document.getAnimations().filter(a=>a.playState==='running').length}));
matrix.push({width,height,reducedMotion,...row});if(row.overflow||row.h1!==1||row.broken.length||row.smallButtons.length||row.outside.length||(reducedMotion==='reduce'&&row.runningAnimations))failures.push(matrix.at(-1));await page.close();
}
const page=await browser.newPage({viewport:{width:390,height:844}});
await page.goto(base,{waitUntil:'networkidle'});await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').innerText(),'Skip to content');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>location.hash),'#main');
await page.getByRole('button',{name:'Menu',exact:false}).click();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Menu',exact:false}).getAttribute('aria-expanded'),'false');assert((await page.locator(':focus').innerText()).includes('Menu'));interactions.navigation=true;
await page.locator('.pl-margin-object').first().click();assert(await page.locator('dialog').evaluate(e=>e.open));await page.keyboard.press('Escape');assert(!(await page.locator('dialog').evaluate(e=>e.open)));assert((await page.locator(':focus').getAttribute('class')).includes('pl-margin-object'));interactions.objectKeyboard=true;
await page.locator('#fyd').scrollIntoViewIfNeeded();await page.locator('.ed-service-list button').first().waitFor();await page.getByRole('button',{name:'Happy Place',exact:true}).click();await page.locator('.ed-service-list button').last().click();await page.locator('.ed-service-detail summary').click();assert((await page.locator('.ed-service-detail').innerText()).includes('website statement'));interactions.fyd=true;
await page.locator('#architecture').scrollIntoViewIfNeeded();for(const node of await page.locator('.pl-flow-node').all()){await node.click();assert.equal(await node.getAttribute('aria-pressed'),'true')};await page.getByRole('button',{name:'Previous concept'}).click();await page.getByRole('button',{name:'Play tour'}).click();await page.waitForTimeout(6800);assert((await page.locator('.pl-play').innerText()).includes('Replay'));await page.getByRole('button',{name:'Replay tour'}).click();await page.waitForTimeout(200);await page.getByRole('button',{name:'Pause tour'}).click();const before=await page.locator('.pl-flow-node[aria-pressed=true]').innerText();await page.waitForTimeout(3400);assert.equal(await page.locator('.pl-flow-node[aria-pressed=true]').innerText(),before);interactions.boundedTourAndPause=true;
for(const button of await page.locator('.pl-primitive-buttons button').all()){await button.click();assert.equal(await button.getAttribute('aria-pressed'),'true')};interactions.primitives=true;
await page.getByLabel('Find a product, capability, or article').fill('not a recorded thing 123');await page.getByRole('button',{name:'Search published knowledge'}).click();assert((await page.locator('.ed-results').innerText()).includes('No published record'));interactions.unknownSearch=true;
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto(base,{waitUntil:'networkidle'});await page.locator('#fyd').scrollIntoViewIfNeeded();await page.locator('.ed-service-list button').first().waitFor();await page.addScriptTag({path:'\\\\wsl.localhost\\Ubuntu\\home\\nolan\\projects\\ping\\node_modules\\axe-core\\axe.min.js'});const result=await page.evaluate(async()=>await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));a11y.push({width,route:'/',violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))})}
for(const route of ['/docs','/blog','/blog/hpp-to-ping-first-tenant','/blog/why-continuity-matters-for-ai-agents','/blog/building-agent-execution-boundaries','/blog/evidence-and-provenance-for-autonomous-systems'])for(const width of [390,1440]){
await page.setViewportSize({width,height:900});const response=await page.goto(base+route,{waitUntil:'networkidle'});assert.equal(response.status(),200);assert.equal(await page.locator('h1').count(),1);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));await page.addScriptTag({path:'\\\\wsl.localhost\\Ubuntu\\home\\nolan\\projects\\ping\\node_modules\\axe-core\\axe.min.js'});const result=await page.evaluate(async()=>await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));a11y.push({width,route,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
}
await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base,{waitUntil:'networkidle'});assert.equal(await page.locator('.pl-play').count(),0);interactions.reducedMotionManualControls=true;
fs.writeFileSync(path.join(__dirname,'public-validation.json'),JSON.stringify({matrix,failures,a11y,errors,interactions},null,2));
console.log(JSON.stringify({matrix:matrix.length,failures,a11y:a11y.filter(x=>x.violations.length),errors,interactions},null,2));
for(const width of [390,1440,1920]){await page.setViewportSize({width,height:900});await page.goto(base,{waitUntil:'networkidle'});await page.locator('#fyd').scrollIntoViewIfNeeded();await page.locator('.ed-service-list button').first().waitFor();await page.evaluate(()=>{document.activeElement?.blur();scrollTo(0,0)});await page.screenshot({path:path.join(__dirname,'new-'+width+'-first.png')});await page.screenshot({path:path.join(__dirname,'new-'+width+'-full.png'),fullPage:true});for(const id of ['architecture','primitives','fyd','journal','problem'])await page.locator('#'+id).screenshot({path:path.join(__dirname,'new-'+width+'-'+id+'.png')})}
for(const route of ['docs','blog'])for(const width of [390,1440]){await page.setViewportSize({width,height:900});await page.goto(base+'/'+route,{waitUntil:'networkidle'});await page.screenshot({path:path.join(__dirname,'new-'+width+'-'+route+'.png')});}
await browser.close();if(failures.length||a11y.some(x=>x.violations.length)||errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
