/**
 * PROD-6 verification (2026-09-27): provenance jargon repair.
 *
 * (a) The site footer visible text contains no "object graph",
 *     "acceptance sequences", "provenance:", or "website-ingestion:".
 * (b) The object overlay visible text contains no "website-derived" and no
 *     raw "website-ingestion:" refs; the raw ref survives only in the
 *     data-provenance-ref DOM attribute (debugging, not visible).
 * (c) The honest epistemic claim is preserved in plain language: everything
 *     on the page comes from the website, not independent verification.
 */
import { renderToStaticMarkup } from "react-dom/server";
import React from "react";
import { ObjectOverlay } from "../object-overlay";
import { RENDERER_INJECTED_CLAIMS } from "../../sitespec/sites-render-audit";
import { provenanceSentence } from "@/app/sites/_shared/site-client";
import type { PingObject } from "@/lib/ping/types";

/** Visible text only: data attributes, tags, and their values are not visible. */
function visibleText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/g, " ")
    .replace(/data-[a-z-]+="[^"]*"/g, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function serviceObject(): PingObject {
  return {
    id: "website-business-1-service-1",
    schema: "ping.social.service@1",
    controllerId: "web:www.coppersmithplumbing.com",
    visibility: "public",
    title: "Plumbing",
    provenance: {
      kind: "website-derived",
      ref: "website-ingestion:https://www.coppersmithplumbing.com/",
      derivedAt: "2026-09-21T13:50:00Z",
    },
    fields: {
      name: "Plumbing",
      claimKind: "website_statement",
    },
    relationships: [],
  } as PingObject;
}

describe("PROD-6: provenance jargon repair", () => {
  test("footer sentence is plain language, keeps the honest epistemic claim", () => {
    const sentence = provenanceSentence({} as never);
    expect(sentence).not.toContain("object graph");
    expect(sentence).not.toContain("acceptance sequences");
    expect(sentence).not.toContain("provenance:");
    expect(sentence).not.toContain("website-ingestion:");
    expect(sentence).toContain("FYD Social");
    expect(sentence).toContain("website");
    expect(sentence).toMatch(/not independent verification/);
  });

  test("audit registry pins the plain-language footer format", () => {
    const claim = RENDERER_INJECTED_CLAIMS.find(
      (c) => c.id === "footer-provenance",
    );
    expect(claim).toBeDefined();
    const template = claim?.template ?? "";
    expect(template).not.toContain("object graph");
    expect(template).not.toContain("acceptance sequences");
    expect(template).toContain(
      "Generated by FYD Social from the business website.",
    );
    expect(template).toMatch(/not independent verification/);
  });

  test("overlay keeps raw provenance in data attributes, never in visible text", () => {
    const object = serviceObject();
    const html = renderToStaticMarkup(
      React.createElement(ObjectOverlay, {
        object,
        graph: { objects: [object], relationships: [] },
        siteId: "test-site",
        onClose: () => {},
      }),
    );
    const text = visibleText(html);
    expect(text).not.toContain("website-derived");
    expect(text).not.toContain("website-ingestion:");
    expect(text).not.toMatch(/provenance:/i);
    // Raw ref preserved for debugging in the DOM, not visible.
    expect(html).toContain(
      'data-provenance-ref="website-ingestion:https://www.coppersmithplumbing.com/"',
    );
  });
});
