/**
 * Render test: compile the generated spec through the real renderer to
 * static HTML, one file per page. The HTML files double as screenshot
 * fixtures (styled with the compiled Tailwind stylesheet).
 *
 * Run: jest render.test.ts ; outputs to /tmp/fyd-render/<slug>.html
 */

import { renderToStaticMarkup } from "react-dom/server";
import * as fs from "fs";
import * as path from "path";
import { SitePageView } from "../renderer";
import { HAPPY_PLACE_GRAPH } from "../../proceduralize/__fixtures__/happy-place-graph";
import { generateSiteSpec } from "../../proceduralize/generator";
import { isRenderable, validateSiteSpec } from "../../sitespec/validator";

const OUT_DIR = "/tmp/fyd-render";
const CSS_PATH = "/tmp/fyd-site.css";

describe("render to static HTML", () => {
  test("every page renders with content, claim badges, and FYD Social branding", () => {
    const spec = generateSiteSpec(HAPPY_PLACE_GRAPH, {
      generatedAt: "2026-09-21T12:00:00.000Z",
      eventSequences: [65, 83],
    });
    const knownSchemas = new Set(HAPPY_PLACE_GRAPH.objects.map((o) => o.schema));
    const findings = validateSiteSpec(spec, knownSchemas);
    expect(isRenderable(findings)).toBe(true);

    const css = fs.existsSync(CSS_PATH) ? fs.readFileSync(CSS_PATH, "utf8") : "";
    fs.mkdirSync(OUT_DIR, { recursive: true });

    const ctx = { spec, graph: HAPPY_PLACE_GRAPH, viewer: { viewerId: null, displayName: null } };
    for (const page of spec.pages) {
      const body = renderToStaticMarkup(SitePageView({ page, ctx }));
      const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${page.title} | FYD Social Generated Site</title>
<style>${css}</style>
</head>
<body class="bg-background">
<header class="border-b border-border-soft bg-background">
<div class="mx-auto max-w-5xl px-4 py-4"><p class="text-xs font-semibold uppercase tracking-widest text-accent">FYD Social</p><h1 class="text-xl font-bold">Generated site demo</h1></div>
<nav class="mx-auto flex max-w-5xl gap-1 px-4 pb-3">${spec.navigation
        .map(
          (n) =>
            `<span class="rounded px-4 py-2 text-sm font-medium ${
              n.pageSlug === page.slug ? "bg-primary text-primary-foreground" : "text-accent"
            }">${n.label}</span>`,
        )
        .join("")}</nav>
</header>
${body}
<footer class="border-t border-border-soft bg-surface"><div class="mx-auto max-w-5xl px-4 py-6 text-sm text-accent"><p>Generated by FYD Social from a website-ingestion object graph (acceptance sequences 65-83). All claims on this page are website statements, never verified fact.</p></div></footer>
<script>window.addEventListener('load',function(){document.title='SW:'+document.documentElement.scrollWidth+',VW:'+window.innerWidth+'|'+document.title});</script>
</body>
</html>`;
      const outPath = path.join(OUT_DIR, page.slug + ".html");
      fs.writeFileSync(outPath, html);
      if (page.slug === "home" || page.slug === "about") {
        expect(body).toContain("Happy Place");
      }
      expect(body).toContain("Website statement");
    }

    const home = fs.readFileSync(path.join(OUT_DIR, "home.html"), "utf8");
    expect(home).toContain("Decks");
    expect(home).toContain("Fences");
    expect(home).toContain("Remodels");
    expect(home).toContain("Home repair and restoration");
    expect(home).toContain("Ask FYD");
    // Contact renders the canonical phone; the hero links the website
    // object through has_website instead of a duplicated field.
    expect(home).toContain("+15412865190");
    expect(home).toContain("https://happy-place-platform.vercel.app/");
    // No invented copy: the old illustrative fixture's inventions are gone.
    expect(home).not.toContain("Custom carpentry");

    const services = fs.readFileSync(path.join(OUT_DIR, "services.html"), "utf8");
    for (const title of ["Decks", "Fences", "Remodels", "Home repair and restoration"]) {
      expect(services).toContain(title);
    }
  });
});
