/**
 * LANE-8: visitor render-chrome test.
 *
 * Renders the real page through SitePageView with a classified visitor
 * context and asserts the forbidden debug concepts are absent from the
 * visitor HTML, while the quiet Source affordance is present. The same
 * page rendered as engineer retains the debug chrome (separate, not
 * deleted).
 */

import { renderToStaticMarkup } from "react-dom/server";
import { SitePageView } from "../renderer";
import { HAPPY_PLACE_RICH_GRAPH } from "../../proceduralize/__fixtures__/happy-place-rich-graph";
import { generateSiteSpec } from "../../proceduralize/generator";
import { isRenderable, validateSiteSpec } from "../../sitespec/validator";
import type { RenderViewerKind } from "../../sitespec/render-projection";

const FORBIDDEN = [
  "Why this?",
  "Site record",
  "Website statement",
  "Demo addition",
  "Feed item",
  "Mixed sources",
  "Generated site demo",
  "Procedural clone proof",
  "acceptance sequences",
  "Generated by FYD Social",
  "Content digest",
];

function renderHome(viewerKind: RenderViewerKind): string {
  const spec = generateSiteSpec(HAPPY_PLACE_RICH_GRAPH, {
    generatedAt: "2026-09-21T12:00:00.000Z",
    eventSequences: [65, 83],
  });
  const knownSchemas = new Set(
    HAPPY_PLACE_RICH_GRAPH.objects.map((o) => o.schema),
  );
  const findings = validateSiteSpec(spec, knownSchemas);
  expect(isRenderable(findings)).toBe(true);
  const page = spec.pages[0];
  const ctx = {
    spec,
    graph: HAPPY_PLACE_RICH_GRAPH,
    viewer: { viewerId: null, displayName: null },
    viewerKind,
  };
  return renderToStaticMarkup(SitePageView({ page, ctx }));
}

describe("visitor render projection", () => {
  test("visitor HTML excludes the forbidden debug concepts", () => {
    const html = renderHome("visitor");
    for (const term of FORBIDDEN) {
      expect(html).not.toContain(term);
    }
  });

  test("visitor HTML carries the quiet Source affordance", () => {
    const html = renderHome("visitor");
    expect(html).toContain(">Source</summary>");
  });

  test("engineer HTML retains the debug chrome", () => {
    const html = renderHome("engineer");
    expect(html).toContain("Why this?");
  });

  test("absent viewerKind fails closed to the quiet treatment", () => {
    const html = renderHome(undefined as unknown as RenderViewerKind);
    expect(html).not.toContain("Why this?");
    expect(html).toContain("Source</summary>");
  });
});
