"use client";
import {useEffect,useRef,useState} from "react";
import {EditorialSymbol} from "./editorial-symbols";
import {PrimitiveArtwork} from "./primitive-artwork";
export interface LearningItem {id?:string;label:string;title?:string;detail?:string;summary?:string;why?:string;consumes?:string;produces?:string;authority?:string;verify?:string;maturity?:string;source?:string;tag?:string;glyph?:string;symbol?:string;example?:string}
export interface LearningIntent {kind:"flow"|"primitives"|"principles"|"problem"|"audiences"|"developer";items:LearningItem[];note?:string}
export function EditorialLearning({intent}:{intent:LearningIntent}){
 const [selected,setSelected]=useState(0),[playing,setPlaying]=useState(false),[reduced,setReduced]=useState(false);
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const m=matchMedia("(prefers-reduced-motion: reduce)");const sync=()=>{setReduced(m.matches);if(m.matches)setPlaying(false)};sync();m.addEventListener("change",sync);const hidden=()=>{if(document.hidden)setPlaying(false)};document.addEventListener("visibilitychange",hidden);const observer=new IntersectionObserver(([e])=>{if(!e.isIntersecting)setPlaying(false)});if(root.current)observer.observe(root.current);return()=>{m.removeEventListener("change",sync);document.removeEventListener("visibilitychange",hidden);observer.disconnect()}},[]);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(selected>=intent.items.length-1)setPlaying(false);else setSelected(i=>i+1)},3200);return()=>clearTimeout(timer)},[playing,selected,intent.items.length]);
 const choose=(n:number)=>{setPlaying(false);setSelected(n)},item=intent.items[selected];if(!item)return null;
 if(intent.kind==="flow")return <div className="pl-flow" ref={root}><div className="pl-flow-top"><span className="ed-label">The compounding loop</span><span className="pl-caption">Conceptual walkthrough · no live activity</span></div><div className="pl-flow-track">{intent.items.map((x,i)=><button key={x.label} aria-pressed={i===selected} onClick={()=>choose(i)} data-active={i===selected} className="pl-flow-node"><span className="pl-flow-index">0{i+1}</span><span className="pl-flow-glyph"><EditorialSymbol concept={x.symbol??x.label} phase={i===selected?2:0}/></span><strong>{x.label}</strong><small>{x.tag}</small></button>)}</div><div className="pl-flow-detail"><div key={selected} className="pl-flow-copy" aria-live={playing?"off":"polite"}><p className="ed-label">0{selected+1} / {item.tag}</p><h3>{item.title}</h3><p>{item.detail}</p></div><div className="pl-flow-controls">{item.example&&<div className="pl-flow-example"><span className="ed-label">Illustrative example / A returning customer</span><p>{item.example}</p></div>}<span className="pl-loop-label">New evidence feeds<br/>the next cycle. ↶</span><div><button onClick={()=>choose(Math.max(0,selected-1))} disabled={selected===0} aria-label="Previous concept">←</button><button onClick={()=>choose(Math.min(intent.items.length-1,selected+1))} disabled={selected===intent.items.length-1} aria-label="Next concept">→</button>{!reduced&&<button className="pl-play" aria-pressed={playing} onClick={()=>{if(selected===intent.items.length-1)setSelected(0);setPlaying(!playing)}}>{playing?"Pause tour":selected===intent.items.length-1?"Replay tour":"Play tour"} <span aria-hidden="true">{playing?"Ⅱ":"▷"}</span></button>}</div></div></div>{intent.note&&<p className="pl-caption pl-flow-note">{intent.note}</p>}</div>;
 if(intent.kind==="primitives")return <div className="pl-primitives" ref={root}><div className="pl-primitive-buttons" aria-label="Choose a primitive">{intent.items.map((x,i)=><button key={x.id??x.label} onClick={()=>choose(i)} aria-pressed={i===selected}><span className="pl-small-glyph"><EditorialSymbol concept={x.symbol??x.id} phase={i===selected?2:0}/></span><strong>{x.label}</strong><span aria-hidden="true">↗</span></button>)}</div><div className="pl-primitive-detail" aria-live="polite"><span className="pl-status">{item.maturity}</span><div className="pl-primitive-giant"><PrimitiveArtwork concept={item.symbol??item.id}/></div><h3>{item.label}</h3><p className="pl-primitive-summary">{item.summary}</p><p>{item.why}</p><dl>{[["Consumes",item.consumes],["Produces",item.produces],["Authority",item.authority]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><details><summary>What can I verify?</summary><p>{item.verify}</p></details><a className="ed-text-link" href={item.source}>Read the field guide <span aria-hidden="true">↗</span></a></div></div>;
 if(intent.kind==="problem")return <div className="pg-context-study"><div className="pg-context-label"><span className="ed-label">Three conversations. One missing history.</span><EditorialSymbol concept="uncertainty"/></div>{intent.items.map((x,i)=><div className="pg-context-record pg-evolve" key={x.label}><span className="pg-context-number">0{i+1}</span><div><span className="ed-label">{x.label}</span><p>{x.detail}</p></div><EditorialSymbol concept={["observation","lineage","continuity"][i]} phase={1}/></div>)}<div className="pg-context-thread"><span/><p>Keep the source.<br/>Carry the context.</p><EditorialSymbol concept="continuity"/></div></div>;
 if(intent.kind==="principles")return <div className="pl-principles">{intent.items.map((x,i)=><article key={x.label} className="pg-evolve"><span className="pl-principle-symbol"><EditorialSymbol concept={x.symbol??["continuity","evidence","capabilities"][i]} phase={1}/></span><p className="ed-label">0{i+1} / {x.label}</p><h3>{x.title}</h3><p>{x.detail}</p></article>)}</div>;
 if(intent.kind==="audiences")return <div className="pl-audiences">{intent.items.map((x,i)=><article key={x.label} className="pg-evolve"><span className="ed-label">0{i+1} / {x.label}</span><h3>{x.title}</h3><p>{x.detail}</p><span className="pl-audience-mark"><EditorialSymbol concept={x.symbol??["lineage","continuity","projection","capabilities"][i]} phase={1}/></span></article>)}</div>;
 return <div className="pl-developer">{intent.items.map(x=><a key={x.label} href={x.source}><span className="ed-label">{x.label}</span><h3>{x.title}<span aria-hidden="true">↗</span></h3><p>{x.detail}</p></a>)}</div>;
}
